### ISSUE TITLE
Not able to edit the shape at all

### ISSUE THREAD

**Issue by nyrrrr** [Goutte/godot-addon-animated-shape-2d#2]
Hi,

I added your plugin, enabled it and then added the new AnimatedShape2D to my player node.
There I selected the animated sprite and collision shape and then added a new ShapeFrame.
![image](https://github.com/Goutte/godot-addon-animated-shape-2d/assets/2575407/7e4078ae-eb8e-4a5f-baa6-dc39a77f5c5c)

When I now open the Animated Shape tab, the animations are listed, but when I click on them nothing happens
![image](https://github.com/Goutte/godot-addon-animated-shape-2d/assets/2575407/591d382a-6242-441d-95cc-da53b8a96038)

There's also a bunch of errors in my output log which might be related to that problem.
![image](https://github.com/Goutte/godot-addon-animated-shape-2d/assets/2575407/f09d9e65-d69d-4802-8b53-63df9cc92819)

Do you have any suggestions on how I can fix that?

**Comment by Goutte** [comment]
Thanks for the bug report !

This looks like the Editor cannot instantiate the frame editor scene.

Did rebooting the Godot Editor solve the issue ?

**Comment by Goutte** [comment]
There was a leftover texture crashing the shape frame editor scene.

You can either grab the new, patched source of the addon, or open the scene `res://addons/goutte.animated_shape_2d/editor/shape_frame_editor.tscn` and let Godot fix it for you.

Do tell me if that works for you (it should).  :rocket:

**Comment by Goutte** [comment]
@nyrrrr Hahaha I did not recognize you :joy:

Thanks again for testing this and taking the time to make a report.
It was a really dumb bug, which I would never have seen because I always open the scenes, even in my blank test project.

I've added you as contributor of the project (it means you can create and assign labels, and make branches, and even commit to main perhaps), since you were the trigger for me to package this.

**Comment by nyrrrr** [comment]
Alright, thanks. :D I will try it out soon

**Comment by Goutte** [comment]
I'm confident this has been fixed, so I'm closing.

> Do reopen if I'm wrong !
