### ISSUE TITLE
Failure when using AnimatedShape2D as root node of a scene

### ISSUE THREAD

**Issue by Margad0413** [Goutte/godot-addon-animated-shape-2d#8]
![screenshot_01](https://github.com/Goutte/godot-addon-animated-shape-2d/assets/76434051/aa76ce86-a924-4e00-b6a3-aa25b3bf19bb)
<img width="956" alt="image" src="https://github.com/Goutte/godot-addon-animated-shape-2d/assets/76434051/abd0985b-f75e-47d9-883d-e88ac7f79c3d">

The animated shape window at the bottom of that photo does not appear at all. What's the problem?

**Comment by Goutte** [comment]
I never tried adding the `AnimatedShape2D` as root node (the issue is here), nor adding nodes as children to it (not the issue).

I can reproduce the issue ; I am investigating it.
Well spotted !

Here's what I get in the error output :

    editor/editor_node.cpp:8240 - Condition "plugins_list.has(p_plugin)" is true.

It's not obvious to me what's going wrong here.

---

As a workaround for now, I'd try using the `AnimatedShape2D` as  **not the root node**.

**Comment by Goutte** [comment]
@Margad0413 Also, that witch is super cute.   :broom: :sparkles:

**Comment by Goutte** [comment]
The error message I get is related to https://github.com/godotengine/godot/issues/83256 .

That's not our issue.

I figured it out : scene root nodes have no `owner`.

I'll patch this at some point, for the `1.4.1` release.

Thanks again for the bug report

**Comment by Goutte** [comment]
I auto-closed this using the commit message ; the fix was submitted to the published addon on the Asset Lib, along with the new 1.4.1 version available here : https://github.com/Goutte/godot-addon-animated-shape-2d/releases/tag/v1.4.1

It's going to be live in a few days at most.
Meanwhile you can download the patched addon from here if you want.

Anyway, you should probably never add `Node2D` as children of plain `Node`s, unless you know what you are doing and really want to reset the transform.

It never occurred to me to do that because it feels … mathematically taboo ?   :grinning: 

Good luck with your game, and do ping me on the fedi when it's live, I want to try it !  _(also, it gives me boasting rights, which is the sole salary I get from doing all this)_
